
data = {
    "questions": [
        {"DigComp": "1.1", "Statement": "I know that different search engines may give different search results, because they are influenced by commercial factors.", "Type": "K", "Level": "I"},
        {"DigComp": "1.1",
            "Statement": "I know which words to use in order to find what I need quickly (e.g. to search online or within a document).", "Type": "K", "Level": "F"},
        {"DigComp": "1.1",
            "Statement": "When I use a search engine, I can take advantage of its advanced features.", "Type": "S", "Level": "I"},
        {"DigComp": "1.1",
            "Statement": "I know how to find a website I have visited before.", "Type": "S", "Level": "F"},
        {"DigComp": "1.2",
            "Statement": "I know how to differentiate promoted content from other content I find or receive online (e.g. recognising an advert on social media or search engines).", "Type": "S", "Level": "I"},
        {"DigComp": "1.2",
            "Statement": "I know how to identify the purpose of an online information source (e.g. to inform, influence, entertain, or sell).", "Type": "S", "Level": "I"},
        {"DigComp": "1.2",
            "Statement": "I critically check if the information I find online is reliable.", "Type": "A", "Level": "I"},
        {"DigComp": "1.2",
            "Statement": "I know that some information on the Internet is false (e.g. fake news).", "Type": "K", "Level": "F"},
        {"DigComp": "1.3",
            "Statement": "I know about different storage media (e.g. internal or external hard disk, USB memory, pen drive, memory card).", "Type": "K", "Level": "I"},
        {"DigComp": "1.3",
            "Statement": "I know how to organise digital content (e.g. documents, images, videos) using folders or tagging to find them back later.", "Type": "S", "Level": "F"},
        {"DigComp": "1.3",
            "Statement": "I know how to copy and move files (e.g. documents, images, videos) between folders, devices or on the cloud.", "Type": "S", "Level": "F"},
        {"DigComp": "1.3",
            "Statement": "I know how to manage and analyse data using software (e.g. sorting, filtering, calculations).", "Type": "S", "Level": "I"},
        {"DigComp": "2.1",
            "Statement": "I know how to send, reply and forward e-mails.", "Type": "S", "Level": "F"},
        {"DigComp": "2.1", "Statement": "I know that many communication services and social media are free of charge because they are paid for by advertising.", "Type": "S", "Level": "F"},
        {"DigComp": "2.1",
            "Statement": "I know how to use advanced videoconferencing features (e.g. moderating, recording audio and video).", "Type": "S", "Level": "I"},
        {"DigComp": "2.1",
            "Statement": "I know which communication tools and services (e.g. phone, email, video conference, text message) are appropriate to use in different circumstances.", "Type": "K", "Level": "F"},
        {"DigComp": "2.2", "Statement": "I am open towards sharing digital content that I think might be interesting and useful to others.", "Type": "A", "Level": "I"},
        {"DigComp": "2.2",
            "Statement": "I know how to use cloud services (e.g. Google Drive, DropBox and OneDrive) to share my files.", "Type": "S", "Level": "I"},
        {"DigComp": "2.2",
            "Statement": "I know how to change who I share content with (e.g. friends, friends of friends, everyone).", "Type": "S", "Level": "I"},
        {"DigComp": "2.2",
            "Statement": "I know how to reference the source of documents (e.g. the author or web address) that I found online.", "Type": "S", "Level": "I"},
        {"DigComp": "2.3",
            "Statement": "I know how to apply for a job using a digital platform (e.g. fill in a form, upload my CV and photo).", "Type": "S", "Level": "F"},
        {"DigComp": "2.3",
            "Statement": "I know that many public services are available on the Internet (e.g. booking a health visit, submitting tax declaration, requesting birth, marriage, residence and other certificates).", "Type": "K", "Level": "I"},
        {"DigComp": "2.3",
            "Statement": "I know how to pay for goods and services that I buy online (e.g. using direct bank transfer, credit/debit cards, other online payment systems).", "Type": "S", "Level": "F"},
        {"DigComp": "2.3",
            "Statement": "It matters to me to debate social or political issues online (e.g. in online forums, news sites, Facebook, Twitter).", "Type": "A", "Level": "I"},
        {"DigComp": "2.4",
            "Statement": "I understand the benefits of remote collaboration (e.g. reduced commuting time).", "Type": "A", "Level": "I"},
        {"DigComp": "2.4",
            "Statement": "I know how to edit a shared, online document.", "Type": "S", "Level": "I"},
        {"DigComp": "2.4", "Statement": "I know how to invite others and give appropriate permissions to collaborate on a shared document.", "Type": "S", "Level": "I"},
        {"DigComp": "2.5", "Statement": "I am aware that I should ask permission from a person before publishing or sharing photos about them.", "Type": "K", "Level": "F"},
        {"DigComp": "2.5",
            "Statement": "I know how to recognise online messages and behaviours that attack certain groups or individuals (e.g. hate speech).", "Type": "S", "Level": "F"},
        {"DigComp": "2.5",
            "Statement": "I can take the right measures if someone is doing the wrong thing online (e.g. an offensive comment, threats).", "Type": "S", "Level": "I"},
        {"DigComp": "2.5",
            "Statement": "I know how to behave online according to the situation (e.g. formal vs informal).", "Type": "K", "Level": "F"},
        {"DigComp": "2.6",
            "Statement": "I know my digital identity is everything that identifies me in online environments (e.g. usernames, likes and posts on social media, petitions signed online).", "Type": "K", "Level": "I"},
        {"DigComp": "2.6", "Statement": "I know how to create a profile in digital environments for personal or professional purposes.", "Type": "S", "Level": "I"},
        {"DigComp": "2.6",
            "Statement": "I know that the EU introduced regulation on The Right to Be Forgotten (i.e. to have one's private information removed from the Internet).", "Type": "K", "Level": "I"},
        {"DigComp": "2.6",
            "Statement": "I know how to configure the settings in my Internet browser to prevent or limit cookies.", "Type": "S", "Level": "A"},
        {"DigComp": "3.1",
            "Statement": "I know how to create and edit digital text files (e.g. Word, OpenDocument, Google Docs).", "Type": "S", "Level": "I"},
        {"DigComp": "3.1",
            "Statement": "I know how to express myself by creating digital content on the Internet (e.g. blog post, video on YouTube).", "Type": "S", "Level": "I"},
        {"DigComp": "3.1", "Statement": "I know how to produce a multimedia presentation with text, images, audio and video elements.", "Type": "S", "Level": "A"},
        {"DigComp": "3.1",
            "Statement": "To express myself, I am careful to choose the right type of digital media depending on the audience and my aim (e.g. using social media to promote a project).", "Type": "A", "Level": "I"},
        {"DigComp": "3.2",
            "Statement": "I am keen to create new digital content by mixing and modifying existing digital resources (e.g. a presentation with photos and a soundtrack found on the Internet).", "Type": "A", "Level": "I"},
        {"DigComp": "3.2",
            "Statement": "I know that some digital content can be reused and reworked legally (e.g. public domain or with Creative Commons licences).", "Type": "K", "Level": "A"},
        {"DigComp": "3.2",
            "Statement": "I know how to edit or make changes to digital content that others have created (e.g. insert a text into an image, edit a wiki).", "Type": "S", "Level": "A"},
        {"DigComp": "3.2",
            "Statement": "I know how to create something new by mixing different types of content (e.g. text and images).", "Type": "S", "Level": "F"},
        {"DigComp": "3.3", "Statement": "I am careful to follow the rules about copyrights and licenses of digital content that I find.", "Type": "A", "Level": "I"},
        {"DigComp": "3.3",
            "Statement": "I know that downloading or sharing digital content (e.g. music, software, films) may have ethical or legal consequences.", "Type": "K", "Level": "I"},
        {"DigComp": "3.3",
            "Statement": "I can detect when digital content is made available illegally (e.g. software, movies, music, books, TV).", "Type": "S", "Level": "I"},
        {"DigComp": "3.3",
            "Statement": "I know which different types of licences apply to the use of digital content (e.g. Creative Commons licences).", "Type": "S", "Level": "A"},
        {"DigComp": "3.4", "Statement": "I am interested in understanding how a task can be broken down into steps so that it can be automated, for example in software or by a robot.", "Type": "A", "Level": "A"},
        {"DigComp": "3.4",
            "Statement": "I know that programming languages (e.g. Python, Visual Basic, Java) are used to provide a digital device instructions to carry out a task.", "Type": "K", "Level": "F"},
        {"DigComp": "3.4",
            "Statement": "I can write scripts, macros and simple applications to automate the execution of a task.", "Type": "S", "Level": "A"},
        {"DigComp": "3.4",
            "Statement": "I know that there could be different algorithmic solutions to accomplish a specific computational task (e.g. sorting and searching).", "Type": "K", "Level": "A"},
        {"DigComp": "4.1",
            "Statement": "I understand the benefits and also the safety risks when using Internet-connected devices or systems (e.g. smart watches, smart home devices).", "Type": "K", "Level": "I"},
        {"DigComp": "4.1", "Statement": "I know about the importance of keeping the operating system, antivirus and other software up-to-date in order to prevent security issues.", "Type": "K", "Level": "I"},
        {"DigComp": "4.1",
            "Statement": "I know how to configure the settings of a firewall on different devices.", "Type": "S", "Level": "A"},
        {"DigComp": "4.1",
            "Statement": "I know how to recover digital information and other content (e.g. photos, contacts) from a backup.", "Type": "S", "Level": "I"},
        {"DigComp": "4.2",
            "Statement": "I know how to restrict or refuse access to my geographical location.", "Type": "S", "Level": "I"},
        {"DigComp": "4.2",
            "Statement": "I know how to identify suspicious e-mail messages that try to obtain my personal data.", "Type": "S", "Level": "I"},
        {"DigComp": "4.2",
            "Statement": "I know how to check that the website where I am asked to provide personal data is secure (e.g. https sites, safety logo or certificate).", "Type": "S", "Level": "I"},
        {"DigComp": "4.2",
            "Statement": "I know which personal data I should not share and display online (e.g. on social media).", "Type": "K", "Level": "I"},
        {"DigComp": "4.2",
            "Statement": "I am careful about checking the privacy policies of the digital services that I use.", "Type": "A", "Level": "I"},
        {"DigComp": "4.3",
            "Statement": "I am aware that I should manage the time I spend on my digital devices.", "Type": "A", "Level": "I"},
        {"DigComp": "4.3",
            "Statement": "I know how to protect myself from unwanted and malicious online encounters and materials (e.g. spam messages, identity theft e-mails).", "Type": "S", "Level": "I"},
        {"DigComp": "4.3",
            "Statement": "I know about digital tools that can help older people or people with special needs.", "Type": "K", "Level": "A"},
        {"DigComp": "4.4", "Statement": "I seek out ways in which digital technologies could help me to live and consume in a more environmentally friendly way.", "Type": "A", "Level": "A"},
        {"DigComp": "4.4",
            "Statement": "I know that old digital devices and consumables (e.g. computers, smartphones, batteries) must be appropriately disposed to minimise their environmental impact.", "Type": "K", "Level": "I"},
        {"DigComp": "4.4",
            "Statement": "I know how to reduce the energy consumption of my devices (e.g. change settings, close apps, turn off wifi).", "Type": "S", "Level": "F"},
        {"DigComp": "4.4",
            "Statement": "I know 'green' behaviours to follow when buying or using digital devices (e.g. purchase devices with Eco-label, restrain from unnecessary printing of digital files, do not leave mobile phones and laptop chargers connected without the device).", "Type": "K", "Level": "I"},
        {"DigComp": "5.1",
            "Statement": "When I face a technical problem, I try step-by-step to identify the problem.", "Type": "A", "Level": "I"},
        {"DigComp": "5.1",
            "Statement": "I know some reasons why a digital device may fail to connect online (e.g. wrong wifi password, airplane mode on).", "Type": "K", "Level": "F"},
        {"DigComp": "5.1",
            "Statement": "When I face a technical problem, I am able to find solutions on the Internet.", "Type": "S", "Level": "I"},
        {"DigComp": "5.1",
            "Statement": "I am able to edit the configurations of the operating system of my digital devices to solve technical problems (e.g. automatic stop/start of services, modify registry keys).", "Type": "S", "Level": "A"},
        {"DigComp": "5.2", "Statement": "I usually try to find out if there is a technology solution that might help me address a personal or professional need.", "Type": "A", "Level": "I"},
        {"DigComp": "5.2",
            "Statement": "I know the main functions of the most common digital devices (computer, tablet, smartphone).", "Type": "K", "Level": "F"},
        {"DigComp": "5.2",
            "Statement": "I know how to select the right tool, device or service to perform a given task (e.g. select a smartphone for my needs, choose a tool for a professional videocall).", "Type": "S", "Level": "A"},
        {"DigComp": "5.2", "Statement": "I know technical solutions that can improve the access and use of digital tools such as language translation, magnification or zoom and text-to-voice functionality.", "Type": "K", "Level": "I"},
        {"DigComp": "5.3", "Statement": "I know that digital technology can be used as a powerful tool to innovate processes and products.", "Type": "K", "Level": "I"},
        {"DigComp": "5.3", "Statement": "I am willing to take part in challenges and contests, aimed at solving intellectual, social or practical problems through digital technologies.", "Type": "A", "Level": "A"},
        {"DigComp": "5.3",
            "Statement": "I can use data tools (e.g. databases, data mining and analysis software) that manage and organize complex information to make decisions and solve problems.", "Type": "S", "Level": "A"},
        {"DigComp": "5.4",
            "Statement": "I am willing to help people in my community improve their digital skills.", "Type": "A", "Level": "I"},
        {"DigComp": "5.4", "Statement": "I am curious about new digital devices and applications and I am keen to experiment with them whenever I find the opportunity.", "Type": "A", "Level": "I"},
        {"DigComp": "5.4",
            "Statement": "I know how to use online learning tools to improve my digital skills (e.g. video tutorial, online courses).", "Type": "S", "Level": "I"},
        {"DigComp": "5.4", "Statement": "I know about new trends in the digital world and how they impact on my personal or professional life.", "Type": "K", "Level": "I"}
    ]
}
